### ISSUE TITLE
starter kit not working

### ISSUE THREAD

**Issue by whaleygeek** [AdventuresInMinecraft/AdventuresInMinecraft-Mac#2]
I tried this latest starter kit and it didn't work out of the box.

macbook-air 11inch, OS 10.10.5 Yosemite

Minecraft was running on an old version and I couldn't get 1.12 to work on the old launcher, it kept crashing with a Java error.

So I followed the instructions at the top of the old launcher and upgraded to the new launcher. I had to rename my old Minecraft in Applications as it would not install properly unless I did that.

I then managed to set up a 1.12 profile and Minecraft ran ok.

Then I tried the Server/StartServer.command and it crashed right at the start with a ClassVer error.

I assumed this was to do with the java version, so I installed the latest Java 8 from the oracle website.

Tried again, same error.

Went to a terminal prompt and typed:

```java -version```

I got this:

```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```

Turns out that even though 1.8 was installed, the terminal was still using the old 1.6, which is the standard Apple version that is pre-installed on the Mac.

So I then followed instructions on the web, went into System Preferences/Java to select my Java version, and it turns out it only listed 1.8, it did not list the old 1.6, so there was no way for me to select the latest. I presume this is because the 1.6 is the pre-installed Apple version, that was loaded at the time the OS was built, and was not installed by the Oracle installer so the Oracle installer doesn't know about it. No obvious way to uninstall the pre-installed Apple version.

Stuff this for a Saturday morning, I thought, so I did a bit of a hack for now...

I copied the Path to 1.8 from the Java configuration console, and went into Server/start.command and hacked it like this to get it working, just so that I can at least test with the latest Minecraft version...

```
#!/bin/bash
cd "$( dirname "$0" )"
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
"$JAVA_HOME/bin/java" -Xmx1024M -jar -DIReallyKnowWhatIAmDoingISwear craftbukkit.jar
```

But this doesn't feel like the right fix, as in the future the user might install a different version of Java and it might go into a different path.

I'll leave you to ponder how to fix this properly so it is resilient to change in the future, but this works for me at the moment, so at least I can get on with code testing.

**Comment by whaleygeek** [comment]
Note both sets of quotes in the path are required, due to the spaces in the folder name. Why is it that people put spaces in filenames, it's shockingly bad practice and causes all sorts of problems in scripts!

**Comment by martinohanlon** [comment]
As discussed, made changes to check java version and provide a 'better error' plus content changes plus we'll put a new section on adventuresinminecraft.github.io
